apiVersion: nais.io/v1alpha1
kind: Application
metadata:
  name: sosialhjelp-oppgaver-api
  namespace: teamdigisos
  labels:
    team: teamdigisos
spec:
  image: {{ image }}
  port: 8080
  liveness:
    path: /isalive
    initialDelay: 10
  readiness:
    path: /isready
    initialDelay: 10
  prometheus:
    enabled: true
    path: /metrics
  replicas:
    min: 2
    max: 4
  resources:
    limits:
      memory: 512Mi
    requests:
      cpu: 50m
      memory: 256Mi
  azure:
    application:
      allowAllUsers: true
      enabled: true
  accessPolicy:
    inbound:
      rules:
        - application: sosialhjelp-oppgaver
          permissions:
            scopes:
              - nks
              - navkontor
  gcp:
    sqlInstances:
      - type: POSTGRES_15
        tier: db-f1-micro
        databases:
          - name: sosialhjelp-oppgaver
            envVarPrefix: DB

