ktor {
    deployment {
        port = 8083
        port = ${?PORT}
    }
    application {
        modules = [ no.nav.sosialhjelp.oppgaver.ApplicationKt.appModule ]
    }
}

auth {
    audience = "local-client-id"
    audience = ${?AZURE_APP_CLIENT_ID}
    issuer = "http://localhost:8888/default"
    issuer = ${?AZURE_OPENID_CONFIG_ISSUER}
    jwksUri = "http://localhost:8888/default/jwks"
    jwksUri = ${?AZURE_OPENID_CONFIG_JWKS_URI}
}

database {
    jdbcUrl = "jdbc:postgresql://localhost:54323/sosialhjelp-oppgaver"
    jdbcUrl = ${?DB_JDBC_URL}
    username = "postgres"
    username = ${?DB_USERNAME}
    password = "postgres"
    password = ${?DB_PASSWORD}
}
